# a DNA motif is defined as a nucleic acid sequence pattern that has some biological significance 
# such as being DNA binding sites for a regulatory protein, i.e., a transcription factor

def motif(dna, to_find):
    location = []
    for i in range(len(dna)):
        if dna[i:i+len(to_find)] == to_find:
            location.append(str(i + 1))
    return " ".join(location)

print(motif("CACCACACACCACACCACCACACAACCACACACCACACAAATTCGACCACACACCACACACCACACACCACACGACCACACACCACACTAACCACACACCACACTCACCACACACCACACCACCACACCAACCACACGTACCACACCACCACACACCACACTGACCACACAAAGTAACACCACACAGACCACACGACCACACACCACACGCCACACCACACACCACACGGTCACTGACACCACACGGGTGAACCACACCACCACCACACGCAAGGTGAGACTCGTCATGTTGCAACCACACACCACACACCACACACCACACGTTACAACCACACCTACCACACTACCACACACCACACGGTACCACACTACCACACACCACACACCACACTAGACCACACATGCACCACACACCACACGACCACACTCACCACACACCACACCTCTACACCACACCACCACACAACCACACATACCACACGGCACCACACACCACACTACCACACTACCACACTCCTACCACACCTAACCACACGTAACCACACTAAGAAGCACCACACCGCACCACACCTCAATCACCACACTAGTACCACACACCACACAACCACACTAACCACACACCACACACCACACGGACCACACCTACCACACAACCACACACCACACCACCACACCACCACACTAACACCACACTGGACCACACAGAACCACACACCACACGCACCACACGTAAACCACACAACCACACACCACACGCACCACACCCTTACCACACTTTCACCACACACAAAGTAACCACACGGGGTTGACCACACACCACACACGCTCCACCACACCAACCACACTGATCACACCACACACCACACACCACACGCTACCACACTTACCACACCCGCGTGATCGGTACTGGGACCACACCGCTCACCACACTTTAA", "ACCACACAC"))
